### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fknop** [fknop/distributor#5]
# Roadmap

* [ ] Add tests for the Phoenix API
* [ ] Add a core client library in TypeScript to communicate with the API
* [ ] Add a Jest adapter 
* [ ] Add more intelligent distribution strategy
